name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Test package installation
      run: |
        npm pack
        mkdir test-install
        cd test-install
        npm init -y
        npm install ../patchworks-*.tgz
        npx patchworks --version
        npx patchworks --help
        
    - name: Run pre-publish script
      run: ./scripts/pre-publish.sh

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level high
      
    - name: Check for outdated dependencies
      run: npm outdated || true

  quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Check package validity
      run: npm pack --dry-run
      
    - name: Validate package.json
      run: |
        node -e "
        const pkg = require('./package.json');
        console.log('✅ Package name:', pkg.name);
        console.log('✅ Version:', pkg.version);
        console.log('✅ Main entry:', pkg.main);
        console.log('✅ Binary:', pkg.bin.patchworks);
        if (!pkg.keywords || pkg.keywords.length < 5) {
          throw new Error('Package needs more keywords for discoverability');
        }
        console.log('✅ Keywords count:', pkg.keywords.length);
        "
        
    - name: Check file permissions
      run: |
        if [[ ! -x dist/bin/patchworks.js ]]; then
          echo "❌ Binary file is not executable"
          exit 1
        fi
        echo "✅ Binary file has correct permissions" 